### ISSUE TITLE
Tyra crashed suddenly and a restart causes this error

### ISSUE THREAD

**Issue by k1aus** [dssg/tyra#73]
python3 run_webapp.py
Failed to import the site module
Traceback (most recent call last):
  File "/mnt/data/public_safety/charlotte_eis/tyra_cmpd_dump/tyra_venv/lib/python3.5/site.py", line 703, in <module>
    main()
  File "/mnt/data/public_safety/charlotte_eis/tyra_cmpd_dump/tyra_venv/lib/python3.5/site.py", line 683, in main
    paths_in_sys = addsitepackages(paths_in_sys)
  File "/mnt/data/public_safety/charlotte_eis/tyra_cmpd_dump/tyra_venv/lib/python3.5/site.py", line 282, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/mnt/data/public_safety/charlotte_eis/tyra_cmpd_dump/tyra_venv/lib/python3.5/site.py", line 204, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/mnt/data/public_safety/charlotte_eis/tyra_cmpd_dump/tyra_venv/lib/python3.5/site.py", line 173, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "/mnt/data/public_safety/charlotte_eis/tyra_cmpd_dump/tyra_venv/lib/python3.5/types.py", line 166, in <module>
    import functools as _functools
  File "/mnt/data/public_safety/charlotte_eis/tyra_cmpd_dump/tyra_venv/lib/python3.5/functools.py", line 23, in <module>
    from weakref import WeakKeyDictionary
  File "/mnt/data/public_safety/charlotte_eis/tyra_cmpd_dump/tyra_venv/lib/python3.5/weakref.py", line 12, in <module>
    from _weakref import (
ImportError: cannot import name '_remove_dead_weakref'

**Comment by tweddielin** [comment]
Did you still have this error after you re-create a new virtualenv?
